### ISSUE TITLE
User story

### ISSUE THREAD

**Issue by michmattera** [michmattera/love-running#3]
In order to **be 100% honest** as a **runner**, I can **post an anonymous comment**.

### Acceptance Criteria:

- Modify comment section so it can be anonymous
- The option should be a checkbox
- I can choose so select that option as default

### Tasks

- [x] Update css and html to add this functionality
- [x] Add tickbox to hide user
- [x] Implement model to receive data and post it
- [ ] Test the functionality
